# Tools for the C Lox implementation

package(
    default_visibility = ["//:__subpackages__"],
)

cc_library(
    name = "line_encoding",
    srcs = ["line_encoding.c"],
    hdrs = ["line_encoding.h"],
    deps = [
        "//:common",
        "//:memory",
    ],
)
